### ISSUE TITLE
Дублирование дерева

### ISSUE THREAD

**Issue by bezumkin** [danyaPostfactum/modx-ajaxmanager#1]
Если кликнуть на ресурс в дереве и потом сохранить его - дерево обновляется и дублируется.

Если сохранить ещё раз - так и остаётся дублированным.

Если перейти на новый ресурс и сохранить его - дублируется ещё раз.

![test](https://f.cloud.github.com/assets/1257284/83484/dc3809a4-63e1-11e2-9ee8-958040b16d3e.png)

**Comment by danyaPostfactum** [comment]
Не могу воспроизвести косяк. По идее AjaxManager не влияет на обновление дерева. Попробуй деактивировать плагин - исчезнет ли проблема. Думаю ты вкурсе, что после деактивации нужно сбросить кэш MODX..

**Comment by bezumkin** [comment]
Да, исчезла. Сейчас проверю на modx-test.com.

**Comment by bezumkin** [comment]
Проблема появляется при установке CRC, типа Articles или Tickets.

Подозреваю, что дело в их плагине, который работает по <b>OnManagerPageInit</b>.

Вот, погляди:
Панель управления   http://s2182.modx-test.com/manager/
Логин  s2182
Пароль    sRHBFC4aCpTE

**Comment by danyaPostfactum** [comment]
Чет не вкурил. Редактирую ресурсы, все ок. Че я упустил? Ща еще в FF потестю (сижу на Chrome).
Нашел другой косяк - тулбар после Articles пропадает. Наверняка что-то коряво в нем сделали. Даже контекстное меню какое то кривое.

**Comment by bezumkin** [comment]
http://www.youtube.com/watch?v=Rv7k-EV3Mlk

В режиме инкогнито, без плагинов. Проверил на 2х сайтах, на разных серверах.

**Comment by danyaPostfactum** [comment]
Ну я и олень. Я пользовался кнопкой Сохранить. В этом случае бага нет. Теперь ясно - при каждом переходе создается еще один обработчик шорткатов. В итоге жмем Ctrl+S и дважды-трижды (и тд) сохраняем ресурс. Причем глюк есть и на пустой системе. Спасибо за проясняющий скринкаст. Буду исправлять.

**Comment by bezumkin** [comment]
Видимо, на пустом сайте я тоже юзал кнопку =)

Рад, что разобрались, ибо плагин очешуительный!

**Comment by danyaPostfactum** [comment]
Исправлено https://github.com/danyaPostfactum/modx-ajaxmanager/commit/52678374f13d5f1edc53ae062d63135bc8077fa1
Спасибо за репорт.
