### ISSUE TITLE
Не работает с Revo 2.3.3

### ISSUE THREAD

**Issue by whitebyte** [danyaPostfactum/modx-ajaxmanager#11]
Свежая установка, AjaxManager 1.2.0-pl, при попытке открыть любой ресурс или элемент в дереве - пустое поле контента. В случае с элементами (чанки, шаблоны  и т.д.) "честная" перезагрузка через F5 помогает, в ресурсах - нет, все равно остается белое поле.
Firebug говорит: 

```
TypeError: b[(intermediate value)] is not a constructor, ext-all.js:21
```

**Comment by j0sky** [comment]
+1

**Comment by SoftAlex** [comment]
+1

**Comment by whitebyte** [comment]
В Revo 2.3.4 снова работает
