### ISSUE TITLE
Multiple users logged into manager = massive amount of locked resources

### ISSUE THREAD

**Issue by exside** [danyaPostfactum/modx-ajaxmanager#2]
Tried out AJAX Manager for the first time and I love it, thanks so much for this and till now it works quite well, also with custom stuff and a lot of extras!

The site I tried it on is actually a medium one with several manager users/editors (around 10) and since I installed AJAX Manager I had to instruct them how the remove_locks menu-action works =))...because every resource load of one user results in each of the visited resources locked for all the other users and it does not get unlocked when leaving the resource. Tried to borrow the code from the remove_locks processor at core/model/modx/processors/system/remove_locks.class.php

``` php
$registry = $this->modx->getService('registry', 'registry.modRegistry');
            if ($registry) {
                $registry->addRegister('locks', 'registry.modDbRegister', array('directory' => 'locks'));
                $registry->locks->connect();
                $registry->locks->subscribe('/resource/');
                $registry->locks->read(array('remove_read' => true, 'poll_limit' => 1, 'msg_limit' => 1000));
            }
```

but had no luck, if I add this to the plugin, the manager starts to reload the whole page again...sorry I can not be more helpful here, but don't see deep enough into ajax manager yet =)....

I also sometimes see some very strange layout stuff happen (a loooot of duplicated form fields / sections), but cannot reproduce it on a regular basis and just F5-ing the manager makes it go away and then it works again as expected...so no separate ticket for that one yet.

**Comment by danyaPostfactum** [comment]
Thank you for bug listing. Fixed by https://github.com/danyaPostfactum/modx-ajaxmanager/commit/26a0a76c718b0326edbfc3062b5a4ae473b8d1e5

As for buggy panel displaying, what browser do you use? It would be better to open new issue for that.
