### ISSUE TITLE
AjaxManager & Babel

### ISSUE THREAD

**Issue by Bitaru** [danyaPostfactum/modx-ajaxmanager#3]
Hi Danya!
At first - thanks alot for this solution! Its realy GREAT!

But i using Babel, and dont have any idea how to make it work with AjaxManager.
Maybe you can publish some solution for?

**Comment by danyaPostfactum** [comment]
Thank you. Proposed patch for this issue: https://github.com/mikrobi/babel/pull/73

**Comment by Bitaru** [comment]
Thanks Danya,
But there core/components/babel/elements/chunks/mgr/babelboxitem.chunk.tpl is and form, and on submit this form page will be reloaded, but no content showed.

**Comment by danyaPostfactum** [comment]
Patch accepted. Thanks to @goldsky

**Comment by danyaPostfactum** [comment]
Next Babel release should work fine with AM
