### ISSUE TITLE
Требования к дополнениям

### ISSUE THREAD

**Issue by Viktorminator** [danyaPostfactum/modx-ajaxmanager#5]
Какие требования к дополнением налагает AjaxManager?
Многие дополнения работают неправильно (перестают работать) после установки аджакс-менеджера. Какие нужно внести изменения или что сделать при разработке, чтобы всё работало.
Пишу в связи с этим https://github.com/artdevue/modxTalks/issues/9
Спасибо

**Comment by danyaPostfactum** [comment]
Требования были перечислены тут: http://modx.im/blog/addons/228.html
На всякий случай продублирую:
1) Контроллеры должны быть на классах, представленных в Revo 2.2
2) Скрипты должны подключаться через $controller->addJavascript, стили через $controller->addCss, а встроенные скрипты и стили — через $controller->addHtml.
3) Ext.onReady вызовы должны добавляться через контроллер(через ->addHtml).
4) В скриптах не должно быть прямого изменения location.href — вместо этого должны быть вызовы MODx.loadPage(action, extraParams), например:

``` javascript
MODx.loadPage(MODx.action['resource/update'], 'template=1&class_key=modDocument')
```

Не уверен что это все, но это основное, что вызывает проблемы. Если возникнут сложности - пишите в сообществах, или можно тут - постараюсь помочь.
