### ISSUE TITLE
Дерево элементов и AjaxManager #2

### ISSUE THREAD

**Issue by Kidokyfe** [danyaPostfactum/modx-ajaxmanager#7]
Суть, в google chrome на странице `/manager/index.php` делаю перезагрузку страницы через **CTRL SHIFT R** (Аппаратная перезагрузка страницы) 

Предположим что у нас дерево ресурсов с такой структурой,

```
Документ 1
Документ 2
Документ 3
```

Далее в дереве ресурсов нажимаю любой ресурс, например на `Докумет 1`. Страница перегружается через ajax. Далее тут же в дереве ресурсов нажимаю на `Документ 3` и пытаюсь перетащить его между `Документ 1` и `Документ 2`, но скрипт залипает на мышке.

**Comment by danyaPostfactum** [comment]
Пожалуйста, не создавайте дубли.
