### ISSUE TITLE
В Revo 2.3 при установленном AjaxManager не работают пункты верхнего меню

### ISSUE THREAD

**Issue by whitebyte** [danyaPostfactum/modx-ajaxmanager#8]
При попытке открыть любой из пунктов верхнего меню выдается ошибка. Например, если попытаться открыть пункт "Приложения -> Установщик", будет ошибка "Could not find action file at: /***/antonp85/whitebyte.ru/public_html/wbcontrol/controllers/default/httpwhitebyteru/wbcontrol/aworkspaces.php" (custom install, /wbcontrol это переименованный каталог /manager). При этом в строке браузера неправильный URL - "http://whitebyte.ru/wbcontrol/?a=http://whitebyte.ru/wbcontrol/?a=workspaces"
![jq1](https://cloud.githubusercontent.com/assets/7704186/3597216/fb1852ba-0cce-11e4-894c-23841fccda81.png)

**Comment by whitebyte** [comment]
Этот баг также присутстует в traditional-установке

**Comment by Ibochkarev** [comment]
Такая же проблема.

**Comment by danyaPostfactum** [comment]
Спасибо за репорты, исправлено https://github.com/danyaPostfactum/modx-ajaxmanager/commit/cba24c323ee42f7da74e1ff7454da196426917e5
На modx.com уже залил.
